management:
  health:
    db.enabled: true
  security:
    enabled: false
  endpoints:
    enabled-by-default: true
    web.enabled: true
    web.base-path: /admin
    web.exposure.include: '*'
  endpoint:
    env.enabled: true
    auditevents.enabled: true
    beans.enabled: true
    conditions.enabled: true
    configprops.enabled: true
    health.enabled: true
    heapdump.enabled: true
    info.enabled: true
    logfile.enabled: true
    mappings.enabled: true
    loggers.enabled: true
    metrics.enabled: true
  cloudfoundry:
    enabled: true

eureka:
  client:
    healthcheck:
      enabled: true
  instance:
    hostname: localhost
    statusPageUrlPath: ${server.servlet.context-path}${management.endpoints.web.base-path}/info
    healthCheckUrlPath: ${server.servlet.context-path}${management.endpoints.web.base-path}/health

spring:
  datasource:
    type: org.apache.commons.dbcp2.BasicDataSource

---
spring:
  profiles: cloud
  cloud:
    services:
      registrationMethod: route

eureka:
  instance:
    hostname: ${vcap.application.uris[0]}

security:
  basic:
    enabled: false
